In [134]:
import numpy as np

In [201]:
X1 = np.random.randn(1000).reshape(1000, 1)
X2 = np.random.randn(1000).reshape(1000, 1)
X3 = np.random.randn(1000).reshape(1000, 1)
#X = np.c_[X1, X2, X3, np.ones((1000, 1))]
X = np.c_[X1, X2, X3]

In [202]:
Y = 5 * X1 + 3 * X2 + 1.5 * X3 + 6

In [203]:
W = np.zeros(4).reshape(4, 1)

In [204]:
from sklearn.model_selection import train_test_split

In [205]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [206]:
def loss(X_train, y_train, W):
    h = X_train.dot(W)
    return (1 / (2*len(Y))) * np.sum(((h-y_train)**2))

In [207]:
def grad(Y, Y_hat):
    return 1/len(Y) * (Y - Y_hat).sum()

In [228]:
def Gradient_Descent(W, b, Y, X, num_iterations = 10000, alpha = 0.001):
    m = len(Y)
    for i in range(num_iterations):
        y_hat = X.dot(W) + b
        Dweight = 1/m *  np.sum(X * (y_hat - Y))
        Dbias = 1/m * np.sum(y_hat - Y)
        W = W - alpha * Dweight
        b = b - alpha * Dbias
    return W, b

In [229]:
W = np.random.rand(3, 1)
b = np.random.rand(1)

In [230]:
W, b = Gradient_Descent(W, b, y_train, X_train)

In [231]:
W, b

(array([[2.79216092],
        [3.44883234],
        [3.10853355]]),
 array([6.0832497]))

In [232]:
from sklearn.metrics import mean_squared_error

In [233]:
mean_squared_error(y_true=y_test, y_pred=X_test.dot(W) + b)

7.936605983944369

In [234]:
import pandas as pd

In [240]:
df = pd.read_csv('train.csv')

In [241]:
df.dropna(inplace=True, axis=1)
df = df.select_dtypes('int64')
Y = df['SalePrice']
df.drop(['SalePrice'], axis=1, inplace=True)
df.drop(['Id'], axis = 1, inplace = True)

In [242]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   LotArea        1460 non-null   int64
 2   OverallQual    1460 non-null   int64
 3   OverallCond    1460 non-null   int64
 4   YearBuilt      1460 non-null   int64
 5   YearRemodAdd   1460 non-null   int64
 6   BsmtFinSF1     1460 non-null   int64
 7   BsmtFinSF2     1460 non-null   int64
 8   BsmtUnfSF      1460 non-null   int64
 9   TotalBsmtSF    1460 non-null   int64
 10  1stFlrSF       1460 non-null   int64
 11  2ndFlrSF       1460 non-null   int64
 12  LowQualFinSF   1460 non-null   int64
 13  GrLivArea      1460 non-null   int64
 14  BsmtFullBath   1460 non-null   int64
 15  BsmtHalfBath   1460 non-null   int64
 16  FullBath       1460 non-null   int64
 17  HalfBath       1460 non-null   int64
 18  BedroomAbvGr   1460 non-null   int64
 19  Kitche

In [251]:
W2 = np.random.randn(33).reshape(33, 1)
b2 = np.random.randn(1)

In [252]:
Y2 = Y2.reshape(1460, 1)

In [255]:
X2 = df.to_numpy()

In [259]:
WH, bH = Gradient_Descent(W2, b2, Y2, X2)

/tmp/ipykernel_15012/1534461038.py:5: RuntimeWarning: overflow encountered in multiply
  Dweight = 1/m *  np.sum(X * (y_hat - Y))
/home/youseef/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


array([nan])